### PR TITLE
Don't treat PC config error as SignalReconnectError

### LINKED ISSUE #1050: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': The RTCPeerConnection's signalingState is 'closed'.
### Describe the bug

I have this issue that I cannot reproduce at all, but get a lot of errors in sentry for. Could you please take a look and point in a direction to how to fix it. Here's the log I can extract from sentry. 

### Reproduction

N/A

### Logs

```shell
[
  {
    "level": "warning",
    "data": {
      "arguments": [
        "websocket closed",
        {
          "code": 1006,
          "identity": "<user_id>",
          "reason": "",
          "room": "room_b",
          "roomSid": "room_sid_b",
          "state": 1,
          "wasClean": false
        }
      ]
    }
  },
  {
    "level": "warning",
    "data": {
      "arguments": [
        "signal disconnected",
        {
          "identity": "<user_id>",
          "room": "room_b",
          "roomSid": "room_sid_b"
        }
      ]
    }
  },
  {
    "level": "info",
    "data": {
      "arguments": [
        "resuming signal connection, attempt 0",
        {
          "identity": "<user_id>",
          "room": "room_b",
          "roomSid": "room_sid_b"
        }
      ]
    }
  },
  {
    "level": "info",
    "data": {
      "arguments": [
        "Resuming signal connection",
        {
          "identity": "<user_id>",
          "room": "room_b",
          "roomSid": "room_sid_b"
        }
      ]
    }
  },
  {
    "level": "error",
    "data": {
      "arguments": [
        "Failed to execute 'setConfiguration' on 'RTCPeerConnection': The RTCPeerConnection's signalingState is 'closed'.",
        {
          "error": "[DOMException]",
          "identity": "<user_id>",
          "room": "room_b",
          "roomSid": "room_sid_b"
        }
      ]
    }
  },
  {
    "level": "warning",
    "data": {
      "arguments": [
        "reconnect disconnected",
        {
          "identity": "<user_id>",
          "room": "room_b",
          "roomSid": "room_sid_b"
        }
      ]
    }
  },
  {
    "level": "error",
    "data": {
      "arguments": [
        "unable to set offer",
        {
          "fields": "[Object]",
          "identity": "<user_id>",
          "room": "room_b",
          "roomSid": "room_sid_b"
        }
      ]
    }
  }
]
```
```


### System Info

```shell
Browser: any, but mostly Chrome
OS: Windows / MacOS
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lukasIO**
closes #1050 

Previously an exception thrown in `pc.setConfiguration` was treated as a `SignalReconnectError` which in turn meant the engine kept trying to resume, while a full reconnect would be the appropriate measure.

### CODE REVIEW

File: src/room/RTCEngine.ts [hunk 1]
```diff
@@ -1029,6 +1025,11 @@ export default class RTCEngine extends (EventEmitter as new () => TypedEventEmit
     }
     this.emit(EngineEvent.SignalResumed);
 
+    if (res) {
```
Comment (lukasIO) [inline src/room/RTCEngine.ts:1028]: I think we should additionally make sure somehow that we actually have a reconnect response at this point.

**Review by boks1971 — APPROVED** [review]

**Comment by lukasIO** [comment]
Added a maximum of 2s waiting period for ReconnectResponse to arrive after signal reconnection has re-established.

File: src/api/SignalClient.ts [hunk 2]
```diff
@@ -356,9 +358,10 @@ export class SignalClient {
               abortSignal?.removeEventListener('abort', abortHandler);
               this.startPingInterval();
               if (resp.message?.case === 'reconnect') {
-                resolve(resp.message?.value);
+                resolve(resp.message.value);
```
Comment (davidzhao) [inline src/api/SignalClient.ts:361]: I'm not following this piece. why do we need to fire off a callback vs just resolving the promise? It seems that the promise is resolved either way with the same value?

Comment (lukasIO) [reply src/api/SignalClient.ts:361]: it can happen that the promise gets resolved a couple of lines down with `undefined` if the message that comes in is not of type `reconnect`. So we'd miss the reconnect response when just looking at the return value of that resolving promise.

File: src/api/SignalClient.ts [hunk 3]
```diff
@@ -356,9 +358,10 @@ export class SignalClient {
...
+                this.onReconnectResponse?.(resp.message.value);
               } else {
-                resolve();
+                resolve(undefined);
```
Comment (lukasIO) [inline src/api/SignalClient.ts:364]: for context to the above comment:

this is line is the culprit. in a reconnect scenario we would resolve a signal reconnect promise with `undefined` instead of the reconnect response, as we consider the first incoming message as a successful signal reconnect.

Comment (davidzhao) [reply src/api/SignalClient.ts:364]: I see, this is handling the case that reconnect is not the most immediate message.

When does that happen? this seems like a rather unexpected behavior.. I think the protocol indicates that Reconnect would need to be the first thing that's sent.. just like JoinResponse.

Comment (lukasIO) [reply src/api/SignalClient.ts:364]: definitely mostly a safe guard. 
if it's unexpected behaviour, we can just throw an error instead of another signal message arrives? 
We'll have to figure out server version support for reconnect response though.

Comment (davidzhao) [reply src/api/SignalClient.ts:364]: yeah, so I'm thinking if we can throw an error if ReconnectResponse comes later than expected. That should trigger a full reconnect sequence.

if the server is sending ReconnectResponse after the initial message, it would be breaking spec. We wouldn't want other clients to implement that behavior.

Comment (lukasIO) [reply src/api/SignalClient.ts:364]: sounds good. Though we cannot reject the promise/throw an error per se after we've resolved the promise already. That will just result in an unhandled exception. 
We could introduce a new error event/callback to handle that. 

Will remove the late response handling parts from the PR for now.

Comment (davidzhao) [reply src/api/SignalClient.ts:365]: cool, sounds good! we can add that separately
