### PR TITLE
Fix missing ScalabilityMode import when using SVC

### LINKED ISSUE #814: ScalabilityMode is not defined
### Describe the bug

this show up when upgraded from 1.12.1 to 1.12.2

### Reproduction

ScalabilityMode is not defined

### Logs

_No response_

### System Info

```shell
livekit client js: 1.12.2
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by davidzhao**
also fixed protobuf type mismatch when a float is put in place of uint32

closes #814

### CODE REVIEW

File: src/room/track/LocalVideoTrack.ts [hunk 1]
```diff
@@ -483,15 +484,16 @@ export function videoLayersFromEncodings(
   if (svc) {
     // svc layers
     /* @ts-ignore */
-    const sm = new ScalabilityMode(encodings[0].scalabilityMode);
+    const encodingSM = encodings[0].scalabilityMode as string;
+    const sm = new ScalabilityMode(encodingSM);
```
Comment (lukasIO) [inline src/room/track/LocalVideoTrack.ts:488]: I wish `ts-ignore` or `ts-expect-error` would allow for specifying the exact error you want to surpress so that we could avoid these issues in the future...

**Review by lukasIO — APPROVED** [review]
